# Generated by Django 5.1.2 on 2025-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValePedagio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissao", models.DateTimeField(auto_now_add=True)),
                ("placa_caminhao", models.CharField(max_length=10)),
                ("fazenda_destino", models.CharField(max_length=100)),
                (
                    "numero_recibo_ida",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "numero_recibo_volta",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "custo_pedagio_ida",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "custo_pedagio_volta",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "custo_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("coordenadas", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
